language: node_js
node_js:
  - "11"

before_install:
- ./scripts/travis/before-install.sh
before_script:
- ./scripts/travis/before-script.sh
cache:
  directories:
  - node_modules

addons:
  s3_region: "eu-west-1"
  artifacts:
    permissions: public-read
    region: "eu-west-1"
    paths:
    - ./dist
    target_paths:
    - /
    - builds/$TRAVIS_BUILD_NUMBER

script:
- ./scripts/travis/test.sh

after_success:
- ./scripts/travis/deploy.sh
- ./scripts/travis/discord-hook.sh success $WEBHOOK_URL
after_failure:
- ./scripts/travis/discord-hook.sh failure $WEBHOOK_URL
